/* exercise-catalog.js — shared global exercise catalog (single source).
   De-duplicated to true mechanical variations (equipment/angle/grip/pattern/rep-style);
   program tags are unioned in data but hidden in the Library/Build-Your-Own UI.
   761 raw entries -> 343 variations. + Strength & Supersets merged: +148 unique
   variations (39 dupes unioned by program tag) -> 491 total. */
var EXERCISES=[
{"name":"Adduction Machine","muscle":"Adductors","programs":["STNDR"],"master":null},
{"name":"Adductor Machine","muscle":"Adductors","programs":["Daily Pump"],"master":null},
{"name":"Back Extension","muscle":"Back","programs":["STNDR","Daily Pump"],"master":null},
{"name":"Barbell Row (Bent Over)","muscle":"Back","programs":["PMC","Daily Pump","STNDR","PSU Football","Strength & Supersets"],"master":"Barbell Row"},
{"name":"Barbell Deadlift","muscle":"Back","programs":["Daily Pump","STNDR","PSU Football","Strength & Supersets"],"master":null},
{"name":"Face Pull (Incline)","muscle":"Back","programs":["PMC","Daily Pump"],"master":"Face Pull"},
{"name":"Barbell Row","muscle":"Back","programs":["Daily Pump","MC","PMC"],"master":"Barbell Row"},
{"name":"Barbell Row (overhand grip)","muscle":"Back","programs":["STNDR"],"master":"Barbell Row"},
{"name":"Barbell Upright Row","muscle":"Back","programs":["Daily Pump","MC","PMC","PSU Football","Strength & Supersets"],"master":"Upright Row"},
{"name":"Barbell Row (Smith, Bent Over)","muscle":"Back","programs":["Daily Pump","STNDR"],"master":"Barbell Row"},
{"name":"Face Pull (Cable)","muscle":"Back","programs":["Daily Pump"],"master":"Face Pull"},
{"name":"Cable Row","muscle":"Back","programs":["PSU Football"],"master":"Seated Cable Row"},
{"name":"Seated Cable Row (Cable, Wide)","muscle":"Back","programs":["Daily Pump","PMC"],"master":"Seated Cable Row"},
{"name":"Upright Row (Cable)","muscle":"Back","programs":["Daily Pump","PMC"],"master":"Upright Row"},
{"name":"Chest-Supported Row (pronated)","muscle":"Back","programs":["Daily Pump"],"master":"T-Bar Row"},
{"name":"Close Grip Cable Rows","muscle":"Back","programs":["STNDR","Strength & Supersets"],"master":"Seated Cable Row"},
{"name":"DB Row (Incline)","muscle":"Back","programs":["MC","PMC","Daily Pump","STNDR"],"master":"DB Row"},
{"name":"DB Seal Row","muscle":"Back","programs":["Daily Pump","PMC"],"master":"DB Row"},
{"name":"DB Row (Slight Incline)","muscle":"Back","programs":["MC","PMC","Daily Pump","Strength & Supersets"],"master":"DB Row"},
{"name":"Double Arm Bent Over DB Row","muscle":"Back","programs":["MC","Strength & Supersets"],"master":"DB Row"},
{"name":"Straight Arm Pulldown","muscle":"Back","programs":["Daily Pump","PMC"],"master":"Straight Arm Pulldown"},
{"name":"Face Pull (Rope)","muscle":"Back","programs":["Daily Pump"],"master":"Face Pull"},
{"name":"Hammer Strength High Row","muscle":"Back","programs":["STNDR","Strength & Supersets"],"master":"Machine Row"},
{"name":"Hammer Strength Seated Row","muscle":"Back","programs":["STNDR"],"master":"Machine Row"},
{"name":"DB Row (High Incline)","muscle":"Back","programs":["Daily Pump","MC","PMC"],"master":"DB Row"},
{"name":"Pull-ups","muscle":"Back","programs":["PSU Football","Daily Pump","MC","STNDR"],"master":"Pull-Up"},
{"name":"Incline Pronated DB Rows","muscle":"Back","programs":["STNDR"],"master":"DB Row"},
{"name":"Lat Pull Down","muscle":"Back","programs":["Daily Pump","PSU Football","STNDR"],"master":"Lat Pulldown"},
{"name":"Lat Pulldown (Wide)","muscle":"Back","programs":["Daily Pump","MC","PMC"],"master":"Lat Pulldown"},
{"name":"Machine Row (Machine)","muscle":"Back","programs":["Daily Pump","PMC"],"master":"Machine Row"},
{"name":"Seated Cable Row (Cable, Seated, Neutral)","muscle":"Back","programs":["STNDR","Daily Pump"],"master":"Seated Cable Row"},
{"name":"Barbell Row (Wide)","muscle":"Back","programs":["PMC"],"master":"Barbell Row"},
{"name":"Pull-Ups (AMRAP warm-up)","muscle":"Back","programs":["Daily Pump"],"master":"Pull-Up"},
{"name":"Reverse Incline Face Pulls","muscle":"Back","programs":["PMC"],"master":"Face Pull"},
{"name":"Reverse Seated Pulldowns","muscle":"Back","programs":["MC"],"master":"Pulldown (misc)"},
{"name":"Pulldown (misc) (Rope)","muscle":"Back","programs":["PMC"],"master":"Pulldown (misc)"},
{"name":"Seated Cable Row (Cable, Seated)","muscle":"Back","programs":["Daily Pump"],"master":"Seated Cable Row"},
{"name":"Seated Cable Row (Cable, Seated, Close)","muscle":"Back","programs":["PMC","Daily Pump"],"master":"Seated Cable Row"},
{"name":"Seated Cable Row (Cable, Seated, Wide)","muscle":"Back","programs":["PMC","Daily Pump"],"master":"Seated Cable Row"},
{"name":"Seated Cable Row (rope attachment)","muscle":"Back","programs":["Daily Pump"],"master":"Seated Cable Row"},
{"name":"Seated Cable Row (Cable, Seated, V-Grip)","muscle":"Back","programs":["Daily Pump"],"master":"Seated Cable Row"},
{"name":"Single Arm Cable Row (Cable, Single Arm)","muscle":"Back","programs":["Daily Pump"],"master":null},
{"name":"Single Arm DB Row","muscle":"Back","programs":["Daily Pump","PMC","STNDR","Strength & Supersets"],"master":"DB Row"},
{"name":"Single Arm Hammer Strength Row","muscle":"Back","programs":["STNDR"],"master":"Machine Row"},
{"name":"Single Arm Hammer Strength Seated Row","muscle":"Back","programs":["STNDR"],"master":"Machine Row"},
{"name":"Standing Double Arm Row","muscle":"Back","programs":["PMC"],"master":"Barbell Row"},
{"name":"Straight Arm Pulldown (Cable)","muscle":"Back","programs":["Daily Pump","PMC"],"master":"Straight Arm Pulldown"},
{"name":"Straight Arm Pulldown (Rope)","muscle":"Back","programs":["STNDR","Daily Pump"],"master":"Straight Arm Pulldown"},
{"name":"T-Bar Row","muscle":"Back","programs":["PMC","STNDR"],"master":"T-Bar Row"},
{"name":"Underhand Bent Over Barbell Rows","muscle":"Back","programs":["STNDR"],"master":"Barbell Row"},
{"name":"Underhand Cable Rows","muscle":"Back","programs":["STNDR"],"master":"Seated Cable Row"},
{"name":"Lat Pulldown (Underhand)","muscle":"Back","programs":["STNDR","Daily Pump"],"master":"Lat Pulldown"},
{"name":"V Grip Cable Rows","muscle":"Back","programs":["Daily Pump"],"master":"Seated Cable Row"},
{"name":"100 Rep Bicep Easy Curl","muscle":"Biceps","programs":["Daily Pump"],"master":null},
{"name":"21s","muscle":"Biceps","programs":["PMC"],"master":null},
{"name":"Alternating DB Curl","muscle":"Biceps","programs":["Daily Pump"],"master":"DB Curl"},
{"name":"Alternating Hammer Curls","muscle":"Biceps","programs":["Daily Pump","STNDR"],"master":"Hammer Curl"},
{"name":"Incline DB Curl (Incline, Alternating)","muscle":"Biceps","programs":["MC","Daily Pump"],"master":"Incline DB Curl"},
{"name":"Alternating Standing Hammer Curl","muscle":"Biceps","programs":["STNDR"],"master":"Hammer Curl"},
{"name":"Barbell Curl","muscle":"Biceps","programs":["Daily Pump","MC"],"master":"Barbell Curl"},
{"name":"Barbell Curl (Close)","muscle":"Biceps","programs":["PMC"],"master":"Barbell Curl"},
{"name":"Barbell Curls (wide grip)","muscle":"Biceps","programs":["PMC","Strength & Supersets"],"master":"Barbell Curl"},
{"name":"Barbell Hammer Curl","muscle":"Biceps","programs":["Daily Pump"],"master":null},
{"name":"Barbell Preacher Curl","muscle":"Biceps","programs":["Daily Pump"],"master":"Barbell Preacher Curl"},
{"name":"Reverse Curl (Reverse)","muscle":"Biceps","programs":["Daily Pump","PMC","STNDR"],"master":null},
{"name":"Wrist Curl (Reverse)","muscle":"Biceps","programs":["Daily Pump","PMC"],"master":"Wrist Curl"},
{"name":"DB Spider Curls","muscle":"Biceps","programs":["PMC","STNDR","MC"],"master":"Spider Curl"},
{"name":"Barbell Wrist Curl","muscle":"Biceps","programs":["Daily Pump","PMC"],"master":"Wrist Curl"},
{"name":"Cable Curl (Cable)","muscle":"Biceps","programs":["Daily Pump","PMC","STNDR"],"master":"Cable Curl"},
{"name":"Hammer Curl (Cable, Hammer)","muscle":"Biceps","programs":["STNDR","Daily Pump"],"master":"Hammer Curl"},
{"name":"Concentration Curl","muscle":"Biceps","programs":["Daily Pump","Strength & Supersets"],"master":"Concentration Curl"},
{"name":"DB Curl (warm-up)","muscle":"Biceps","programs":["Daily Pump"],"master":"DB Curl"},
{"name":"Hammer Curl (Hammer)","muscle":"Biceps","programs":["MC","PMC","Daily Pump"],"master":"Hammer Curl"},
{"name":"Double Arm Hammer Preacher Curl","muscle":"Biceps","programs":["Daily Pump"],"master":"Machine Preacher Curl"},
{"name":"Incline DB Curl (Incline)","muscle":"Biceps","programs":["PMC","Daily Pump","STNDR"],"master":"Incline DB Curl"},
{"name":"Hammer Curl (Incline, Hammer)","muscle":"Biceps","programs":["PMC","Daily Pump"],"master":"Hammer Curl"},
{"name":"EZ Bar Curl (EZ Bar)","muscle":"Biceps","programs":["Daily Pump","PSU Football"],"master":null},
{"name":"EZ Bar Spider Curl","muscle":"Biceps","programs":["STNDR"],"master":"Spider Curl"},
{"name":"Floor Cable Concentration Curl *","muscle":"Biceps","programs":["Daily Pump"],"master":"Concentration Curl"},
{"name":"Floor Seated Cable Curl","muscle":"Biceps","programs":["Daily Pump"],"master":"Cable Curl"},
{"name":"Spider Curl (Incline)","muscle":"Biceps","programs":["Daily Pump"],"master":"Spider Curl"},
{"name":"Machine Preacher Curl (Machine)","muscle":"Biceps","programs":["Daily Pump","PMC","STNDR"],"master":"Machine Preacher Curl"},
{"name":"Pinwheel Curls","muscle":"Biceps","programs":["MC","PMC"],"master":"Hammer Curl"},
{"name":"Preacher Curls","muscle":"Biceps","programs":["Daily Pump","MC","PMC","Strength & Supersets"],"master":"Machine Preacher Curl"},
{"name":"Barbell Preacher Curl (Reverse)","muscle":"Biceps","programs":["Daily Pump"],"master":"Barbell Preacher Curl"},
{"name":"Seated Alternating DB Curl","muscle":"Biceps","programs":["PMC"],"master":"DB Curl"},
{"name":"Seated Barbell Curl","muscle":"Biceps","programs":["Daily Pump"],"master":"Barbell Curl"},
{"name":"DB Curl (Seated)","muscle":"Biceps","programs":["Daily Pump"],"master":"DB Curl"},
{"name":"Hammer Curl (Seated, Hammer)","muscle":"Biceps","programs":["Daily Pump"],"master":"Hammer Curl"},
{"name":"Single Arm Cable Curls","muscle":"Biceps","programs":["Daily Pump","Strength & Supersets"],"master":"Cable Curl"},
{"name":"Single Arm Dumbbell Concentration Curl","muscle":"Biceps","programs":["Daily Pump"],"master":"Concentration Curl"},
{"name":"Single Arm Preacher Curl","muscle":"Biceps","programs":["STNDR"],"master":"Machine Preacher Curl"},
{"name":"Standing Barbell Curls (wide grip)","muscle":"Biceps","programs":["Daily Pump"],"master":"Barbell Curl"},
{"name":"Standing Behind the Back Wrist Curl","muscle":"Biceps","programs":["PMC"],"master":"Wrist Curl"},
{"name":"Standing Double Arm Curl","muscle":"Biceps","programs":["Daily Pump"],"master":"DB Curl"},
{"name":"Calf Raises","muscle":"Calves","programs":["MC","PMC"],"master":"Calf Raise"},
{"name":"Seated Calf Raise (feet neutral)","muscle":"Calves","programs":["Daily Pump"],"master":"Calf Raise"},
{"name":"Seated Calf Raises","muscle":"Calves","programs":["PMC","STNDR","Strength & Supersets"],"master":"Calf Raise"},
{"name":"Calf Raise (Standing)","muscle":"Calves","programs":["STNDR","Daily Pump","Strength & Supersets"],"master":"Calf Raise"},
{"name":"Standing Calf Raise (feet neutral)","muscle":"Calves","programs":["Daily Pump"],"master":"Calf Raise"},
{"name":"Standing Smith Machine Calf Raises","muscle":"Calves","programs":["PMC"],"master":"Calf Raise"},
{"name":"Battle Ropes Phase 1 — Basic","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Battle Ropes — Advanced Level 1","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Battle Ropes — Advanced Level 2","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Battle Ropes — Advanced Level 3","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Battle Ropes — Intermediate","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Burpees","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Jump Rope","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Run","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Walk the Line","muscle":"Cardio","programs":["Faint of Heart"],"master":null},
{"name":"Incline DB (Incline, Alternating)","muscle":"Chest","programs":["PMC"],"master":"Incline DB Press"},
{"name":"Barbell Bench (1-1/4 reps)","muscle":"Chest","programs":["PMC"],"master":"Barbell Bench Press"},
{"name":"Barbell Bench","muscle":"Chest","programs":["MC","PMC","Daily Pump","PSU Football"],"master":"Barbell Bench Press"},
{"name":"Barbell Bench (underhand grip)","muscle":"Chest","programs":["PMC"],"master":"Barbell Bench Press"},
{"name":"Close Grip Bench (Close)","muscle":"Chest","programs":["MC","PMC","Daily Pump","STNDR"],"master":"Close Grip Bench"},
{"name":"Barbell Floor Press","muscle":"Chest","programs":["Daily Pump"],"master":"Barbell Bench Press"},
{"name":"DB 21","muscle":"Forearms","programs":["MC","PMC","STNDR","Faint of Heart"],"master":"Forearm Curl"},
{"name":"Rear Delt Fly (Bent Over)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Rear Delt Fly"},
{"name":"Push-Up","muscle":"Chest","programs":["Daily Pump","PMC","PSU Football"],"master":"Push-Up"},
{"name":"Machine Chest (Cable, Standing)","muscle":"Chest","programs":["Daily Pump"],"master":"Machine Chest Press"},
{"name":"Chest Fly (Cable)","muscle":"Chest","programs":["Daily Pump"],"master":"Chest Fly"},
{"name":"Rear Delt Fly (Cable)","muscle":"Shoulders","programs":["Daily Pump","STNDR"],"master":"Rear Delt Fly"},
{"name":"Dips","muscle":"Chest","programs":["Daily Pump","MC","STNDR"],"master":"Dip"},
{"name":"Flat DB Flies","muscle":"Chest","programs":["MC","PMC","STNDR","PSU Football","Daily Pump","Strength & Supersets"],"master":"Chest Fly"},
{"name":"DB Flat Bench","muscle":"Chest","programs":["Daily Pump","PMC","STNDR","Strength & Supersets"],"master":"DB Bench Press"},
{"name":"DB Bench (Floor)","muscle":"Chest","programs":["PMC"],"master":"DB Bench Press"},
{"name":"Incline DB (Incline, Hammer)","muscle":"Chest","programs":["PMC","Daily Pump"],"master":"Incline DB Press"},
{"name":"Incline DB (Incline)","muscle":"Chest","programs":["PSU Football","Daily Pump"],"master":"Incline DB Press"},
{"name":"DB Pullover","muscle":"Chest","programs":["STNDR","Daily Pump","Strength & Supersets"],"master":null},
{"name":"Skull Crusher (Decline)","muscle":"Triceps","programs":["Daily Pump"],"master":"Skull Crusher"},
{"name":"Chest Fly (Cable, Decline)","muscle":"Chest","programs":["Daily Pump","STNDR"],"master":"Chest Fly"},
{"name":"Decline Chest Press","muscle":"Chest","programs":["STNDR"],"master":"Machine Chest Press"},
{"name":"Decline Dumbbell Press","muscle":"Chest","programs":["Daily Pump"],"master":null},
{"name":"Decline Machine Press","muscle":"Chest","programs":["STNDR","Strength & Supersets"],"master":"Machine Chest Press"},
{"name":"Decline Push-Up","muscle":"Chest","programs":["Daily Pump"],"master":"Push-Up"},
{"name":"Dip Machine","muscle":"Chest","programs":["Daily Pump"],"master":"Dip"},
{"name":"Dumbbell Floor Press (hammer grip)","muscle":"Chest","programs":["Daily Pump"],"master":"DB Bench Press"},
{"name":"Flat Bench Hammer Press","muscle":"Chest","programs":["Daily Pump"],"master":"Incline DB Press"},
{"name":"DB Skullcrushers","muscle":"Triceps","programs":["Daily Pump","PMC","STNDR","MC"],"master":"Skull Crusher"},
{"name":"Flat Chest Press","muscle":"Chest","programs":["STNDR"],"master":"Machine Chest Press"},
{"name":"Flat Dumbbell Press (neutral grip)","muscle":"Chest","programs":["Daily Pump"],"master":"DB Bench Press"},
{"name":"DB Bench (Hammer)","muscle":"Chest","programs":["STNDR"],"master":"DB Bench Press"},
{"name":"Machine Chest (Machine)","muscle":"Chest","programs":["PMC","Daily Pump"],"master":"Machine Chest Press"},
{"name":"Machine Chest (Hammer)","muscle":"Chest","programs":["STNDR"],"master":"Machine Chest Press"},
{"name":"Machine Chest (Decline, Hammer)","muscle":"Chest","programs":["STNDR"],"master":"Machine Chest Press"},
{"name":"Hammer Strength Incline Press","muscle":"Chest","programs":["STNDR"],"master":"Machine Chest Press"},
{"name":"High Incline DB Bench","muscle":"Chest","programs":["PMC"],"master":"Incline Barbell Press"},
{"name":"High Incline DB Flies","muscle":"Chest","programs":["MC","PMC","Strength & Supersets"],"master":"Chest Fly"},
{"name":"High Incline DB Press","muscle":"Chest","programs":["MC","PMC","Strength & Supersets"],"master":"Incline DB Press"},
{"name":"Incline Barbell (Incline)","muscle":"Chest","programs":["Daily Pump","PMC","STNDR","PSU Football"],"master":"Incline Barbell Press"},
{"name":"Front Raise (Incline)","muscle":"Shoulders","programs":["PMC","MC"],"master":"Front Raise"},
{"name":"Chest Fly (Cable, Incline)","muscle":"Chest","programs":["Daily Pump","PMC","STNDR"],"master":"Chest Fly"},
{"name":"Incline Bench Cable Fly (pronated)","muscle":"Chest","programs":["Daily Pump"],"master":"Chest Fly"},
{"name":"Incline Bench Pushdowns","muscle":"Triceps","programs":["Daily Pump"],"master":"Tricep Pushdown"},
{"name":"Skull Crusher (Incline)","muscle":"Triceps","programs":["Daily Pump","STNDR","PMC"],"master":"Skull Crusher"},
{"name":"Incline Chest Flies","muscle":"Chest","programs":["MC"],"master":"Chest Fly"},
{"name":"Machine Chest (Machine, Incline)","muscle":"Chest","programs":["PMC","Daily Pump"],"master":"Machine Chest Press"},
{"name":"Kneeling Reverse Forearm Curls (bench supported)","muscle":"Forearms","programs":["MC","PMC"],"master":"Forearm Curl"},
{"name":"Lying Flat Bench Supermans","muscle":"Chest","programs":["Daily Pump"],"master":null},
{"name":"Chest Fly (Machine)","muscle":"Chest","programs":["PMC"],"master":"Chest Fly"},
{"name":"Dumbbell Side Lateral","muscle":"Shoulders","programs":["MC","PMC","Daily Pump"],"master":"Side Lateral Raise"},
{"name":"Pin Rack Bench","muscle":"Chest","programs":["Daily Pump"],"master":"Barbell Bench Press"},
{"name":"Chest Fly (Pronated)","muscle":"Chest","programs":["MC","PMC"],"master":"Chest Fly"},
{"name":"Pronated Incline DB Flies","muscle":"Chest","programs":["STNDR","Strength & Supersets"],"master":"Chest Fly"},
{"name":"Rear Delt Fly (Incline)","muscle":"Shoulders","programs":["Daily Pump","STNDR"],"master":"Rear Delt Fly"},
{"name":"Rear Delt Fly (Reverse)","muscle":"Shoulders","programs":["MC","Daily Pump","PMC"],"master":"Rear Delt Fly"},
{"name":"Reverse Incline Bench Concentration Curls","muscle":"Biceps","programs":["Daily Pump"],"master":"Concentration Curl"},
{"name":"Spider Curl (Reverse Incline, Reverse)","muscle":"Biceps","programs":["Daily Pump"],"master":"Spider Curl"},
{"name":"Rear Delt Fly (Reverse Incline, Reverse)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Rear Delt Fly"},
{"name":"Seated Bent Over Rear Delt DB Fly","muscle":"Shoulders","programs":["Daily Pump"],"master":"Rear Delt Fly"},
{"name":"Chest Fly (Cable, Seated)","muscle":"Chest","programs":["STNDR"],"master":"Chest Fly"},
{"name":"Seated DB Press","muscle":"Chest","programs":["Daily Pump"],"master":"DB Bench Press"},
{"name":"Seated Dip Machine","muscle":"Chest","programs":["STNDR"],"master":"Dip"},
{"name":"Single Arm DB Press (AMRAP)","muscle":"Chest","programs":["MC","Strength & Supersets"],"master":"DB Bench Press"},
{"name":"Single Arm Machine Press","muscle":"Chest","programs":["Daily Pump"],"master":"Machine Chest Press"},
{"name":"Chest Fly (Slight Incline)","muscle":"Chest","programs":["PMC","MC","Daily Pump"],"master":"Chest Fly"},
{"name":"Incline DB (Slight Incline)","muscle":"Chest","programs":["Daily Pump","PMC","MC"],"master":"Incline DB Press"},
{"name":"Incline DB (Slight Incline, Hammer)","muscle":"Chest","programs":["PMC"],"master":"Incline DB Press"},
{"name":"Slight Incline Dumbbell Fly (pronated)","muscle":"Chest","programs":["Daily Pump"],"master":"Chest Fly"},
{"name":"Slight Incline Dumbbell Press (neutral grip)","muscle":"Chest","programs":["Daily Pump"],"master":"Incline DB Press"},
{"name":"Slight Incline Smith Machine Press","muscle":"Chest","programs":["Daily Pump"],"master":"Incline DB Press"},
{"name":"Close Grip Bench (Smith, Close)","muscle":"Chest","programs":["Daily Pump","PMC"],"master":"Close Grip Bench"},
{"name":"Smith Machine Flat Bench Press","muscle":"Chest","programs":["Daily Pump"],"master":"Close Grip Bench"},
{"name":"Shoulder (Cable, Standing)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shoulder Press"},
{"name":"Tricep Cable Press Down (V grip)","muscle":"Triceps","programs":["Daily Pump"],"master":"Tricep Pushdown"},
{"name":"Tricep Machine (Machine)","muscle":"Triceps","programs":["MC","PMC","Daily Pump"],"master":"Tricep Machine"},
{"name":"Ab Wheel Rollout","muscle":"Core","programs":["STNDR"],"master":null},
{"name":"Abdominals","muscle":"Core","programs":["PSU Football"],"master":null},
{"name":"DB Twists","muscle":"Core","programs":["PMC","Strength & Supersets"],"master":null},
{"name":"GHD","muscle":"Core","programs":["PSU Football"],"master":null},
{"name":"Hanging Leg Raises","muscle":"Core","programs":["STNDR"],"master":null},
{"name":"Heavy Bag","muscle":"Core","programs":["Faint of Heart"],"master":null},
{"name":"Heels to Heaven","muscle":"Core","programs":["PMC"],"master":null},
{"name":"High Pull Cable Crunch","muscle":"Core","programs":["STNDR"],"master":null},
{"name":"In & Outs","muscle":"Core","programs":["PMC"],"master":null},
{"name":"Jumping Jacks","muscle":"Core","programs":["Faint of Heart"],"master":null},
{"name":"Plank","muscle":"Core","programs":["STNDR"],"master":null},
{"name":"Shadow Boxing","muscle":"Core","programs":["Faint of Heart"],"master":null},
{"name":"Side Plank","muscle":"Core","programs":["PMC"],"master":null},
{"name":"Sit-Ups (AMRAP)","muscle":"Core","programs":["Faint of Heart"],"master":null},
{"name":"Supermans","muscle":"Core","programs":["MC","PMC"],"master":null},
{"name":"USA Kettlebell Twist","muscle":"Core","programs":["PMC"],"master":null},
{"name":"USA Twists","muscle":"Core","programs":["PMC"],"master":null},
{"name":"Cable Cross Over (pronated grip)","muscle":"Forearms","programs":["Daily Pump"],"master":"Pronated Fly / Pulldown"},
{"name":"Chest Fly Machine (pronated grip)","muscle":"Forearms","programs":["MC","PMC"],"master":"Pronated Fly / Pulldown"},
{"name":"Lat Pulldown (Close)","muscle":"Back","programs":["Daily Pump"],"master":"Lat Pulldown"},
{"name":"D Grip Tricep Pushdowns","muscle":"Forearms","programs":["Daily Pump"],"master":"Forearm Pushdown"},
{"name":"Pronated Fly / Pulldown (Pronated)","muscle":"Forearms","programs":["PMC"],"master":"Pronated Fly / Pulldown"},
{"name":"EZ Bar Medium Grip","muscle":"Forearms","programs":["STNDR"],"master":"Forearm Curl"},
{"name":"Lat Pulldown (Reverse)","muscle":"Back","programs":["Daily Pump","PMC"],"master":"Lat Pulldown"},
{"name":"Lat Pulldown (neutral grip)","muscle":"Back","programs":["Daily Pump"],"master":"Lat Pulldown"},
{"name":"Lat Pulldown (V-Grip)","muscle":"Back","programs":["Daily Pump","PMC","Strength & Supersets"],"master":"Lat Pulldown"},
{"name":"Neutral Grip Tricep Pushdowns","muscle":"Forearms","programs":["PMC"],"master":"Forearm Pushdown"},
{"name":"Forearm Pulldown (Wide)","muscle":"Forearms","programs":["Daily Pump","STNDR"],"master":"Forearm Pulldown"},
{"name":"Reverse Grip Pulldowns","muscle":"Forearms","programs":["MC","PMC"],"master":"Forearm Pulldown"},
{"name":"Forearm Pushdown (Reverse)","muscle":"Forearms","programs":["PMC"],"master":"Forearm Pushdown"},
{"name":"Seated Double Arm DB Front Raise (hammer grip)","muscle":"Forearms","programs":["Daily Pump"],"master":"Forearm Pulldown"},
{"name":"Slight Incline Dumbbell Fly (pronated grip)","muscle":"Forearms","programs":["Daily Pump"],"master":"Pronated Fly / Pulldown"},
{"name":"Forearm Pushdown (V-Grip)","muscle":"Forearms","programs":["Daily Pump","PMC"],"master":"Forearm Pushdown"},
{"name":"V Grip Pulldowns","muscle":"Forearms","programs":["MC","PMC"],"master":"Forearm Pulldown"},
{"name":"Weighted Pull Up (hammer grip)","muscle":"Forearms","programs":["Daily Pump"],"master":"Forearm Pulldown"},
{"name":"Wide Grip Tricep Pulldowns","muscle":"Forearms","programs":["MC"],"master":"Forearm Pushdown"},
{"name":"Barbell Snatch Shrug","muscle":"Full Body","programs":["Daily Pump"],"master":null},
{"name":"Hang Clean","muscle":"Full Body","programs":["PSU Football"],"master":null},
{"name":"Power Clean","muscle":"Full Body","programs":["PSU Football"],"master":null},
{"name":"Barbell Hip Thrust","muscle":"Legs - Glutes","programs":["Daily Pump"],"master":null},
{"name":"Barbell Tricep Kickbacks","muscle":"Legs - Glutes","programs":["Daily Pump"],"master":"Glute Kickback"},
{"name":"Bent Over DB Tricep Kickbacks","muscle":"Legs - Glutes","programs":["MC","PMC"],"master":"Glute Kickback"},
{"name":"Double Arm Cable Tricep Kickbacks","muscle":"Legs - Glutes","programs":["PMC"],"master":"Glute Kickback"},
{"name":"Lying DB Kickbacks","muscle":"Legs - Glutes","programs":["Daily Pump"],"master":"Glute Kickback"},
{"name":"Seated Double Arm DB Kickbacks","muscle":"Legs - Glutes","programs":["Daily Pump"],"master":"Glute Kickback"},
{"name":"Single Arm Tricep Kickbacks","muscle":"Legs - Glutes","programs":["Daily Pump"],"master":"Glute Kickback"},
{"name":"DB RDLs","muscle":"Legs - Hamstrings","programs":["PMC","STNDR","Daily Pump","MC","PSU Football"],"master":"RDL"},
{"name":"Barbell Good Mornings","muscle":"Legs - Hamstrings","programs":["Daily Pump","MC","PMC","Strength & Supersets"],"master":"Good Morning"},
{"name":"Flat Bench Dumbbell Leg Curl","muscle":"Legs - Hamstrings","programs":["Daily Pump","STNDR"],"master":"Leg Curl"},
{"name":"Leg Curl (Lying)","muscle":"Legs - Hamstrings","programs":["PMC","Daily Pump","STNDR","Strength & Supersets"],"master":"Leg Curl"},
{"name":"Reverse Lying Leg Curl Hip Thrust","muscle":"Legs - Hamstrings","programs":["Daily Pump"],"master":"Leg Curl"},
{"name":"Seated Barbell Good Morning (outside shoulder width)","muscle":"Legs - Hamstrings","programs":["Daily Pump"],"master":"Good Morning"},
{"name":"Leg Curl (Seated)","muscle":"Legs - Hamstrings","programs":["MC","PMC","Daily Pump"],"master":"Leg Curl"},
{"name":"Stiff Leg Deadlift (using seated cable row)","muscle":"Legs - Hamstrings","programs":["Daily Pump"],"master":"RDL"},
{"name":"Barbell Back Squat","muscle":"Legs - Quads","programs":["Daily Pump","STNDR","MC","PSU Football"],"master":"Barbell Squat"},
{"name":"Barbell Squat (neutral stance)","muscle":"Legs - Quads","programs":["PMC"],"master":"Barbell Squat"},
{"name":"Barbell Squat (Wide)","muscle":"Legs - Quads","programs":["PMC"],"master":"Barbell Squat"},
{"name":"DB Walking Lunges","muscle":"Legs - Quads","programs":["Daily Pump","STNDR","PMC","Strength & Supersets"],"master":null},
{"name":"Barbell Squat (Close)","muscle":"Legs - Quads","programs":["PMC","Daily Pump"],"master":"Barbell Squat"},
{"name":"Leg Extension","muscle":"Legs - Quads","programs":["Daily Pump","PMC"],"master":"Leg Extension"},
{"name":"Bodyweight Sissy Squat","muscle":"Legs - Quads","programs":["Daily Pump","Strength & Supersets"],"master":null},
{"name":"Same Leg Step-Ups","muscle":"Legs - Quads","programs":["MC","PMC"],"master":null},
{"name":"DB Bulg. Split Squat","muscle":"Legs - Quads","programs":["STNDR","PSU Football","MC"],"master":"Split Squat"},
{"name":"Hack Squat","muscle":"Legs - Quads","programs":["Daily Pump","MC","STNDR","PMC"],"master":"Hack Squat"},
{"name":"Cannonball Smith Machine Squats","muscle":"Legs - Quads","programs":["PMC","Strength & Supersets"],"master":"Hack Squat"},
{"name":"DB Goblet Squat","muscle":"Legs - Quads","programs":["PMC","STNDR","Daily Pump","MC"],"master":"Goblet Squat"},
{"name":"Close Stance Cannonball Leg Press (heels elevated)","muscle":"Legs - Quads","programs":["PMC"],"master":"Leg Press"},
{"name":"Goblet Squat (Close)","muscle":"Legs - Quads","programs":["Daily Pump"],"master":"Goblet Squat"},
{"name":"Goblet Squat (Neutral)","muscle":"Legs - Quads","programs":["PMC","MC"],"master":"Goblet Squat"},
{"name":"Goblet Squats (wide stance, toes pointed out)","muscle":"Legs - Quads","programs":["PMC"],"master":"Goblet Squat"},
{"name":"Hack Squat (Close)","muscle":"Legs - Quads","programs":["Daily Pump","STNDR"],"master":"Hack Squat"},
{"name":"Leg Extension (Neutral)","muscle":"Legs - Quads","programs":["Daily Pump"],"master":"Leg Extension"},
{"name":"Leg Press","muscle":"Legs - Quads","programs":["MC","PMC","STNDR","Daily Pump"],"master":"Leg Press"},
{"name":"Leg (Wide)","muscle":"Legs - Quads","programs":["PMC","Daily Pump"],"master":"Leg Press"},
{"name":"Neutral Stance Leg Press","muscle":"Legs - Quads","programs":["PMC"],"master":"Leg Press"},
{"name":"Seated Leg Extension","muscle":"Legs - Quads","programs":["PMC"],"master":"Leg Extension"},
{"name":"Smith Machine Squat (Smith)","muscle":"Legs - Quads","programs":["Daily Pump"],"master":null},
{"name":"Smith Machine Split Squat","muscle":"Legs - Quads","programs":["PMC","Strength & Supersets"],"master":"Split Squat"},
{"name":"Front Raise (Alternating)","muscle":"Shoulders","programs":["MC","Daily Pump"],"master":"Front Raise"},
{"name":"Arnold Press","muscle":"Shoulders","programs":["MC","PMC","Strength & Supersets"],"master":"Arnold Press"},
{"name":"Around the Worlds","muscle":"Shoulders","programs":["PMC"],"master":null},
{"name":"Band IR/ER","muscle":"Shoulders","programs":["PSU Football"],"master":null},
{"name":"DB Front Raises","muscle":"Shoulders","programs":["Daily Pump"],"master":"Front Raise"},
{"name":"Shoulder (Standing)","muscle":"Shoulders","programs":["Daily Pump","STNDR"],"master":"Shoulder Press"},
{"name":"Barbell Rack Front Raises","muscle":"Shoulders","programs":["Daily Pump"],"master":"Front Raise"},
{"name":"DB Shrug","muscle":"Shoulders","programs":["Daily Pump","MC","PSU Football","Strength & Supersets"],"master":"Shrug"},
{"name":"Shrug (Wide)","muscle":"Shoulders","programs":["PMC"],"master":"Shrug"},
{"name":"Barbell Shrugs (neutral grip)","muscle":"Shoulders","programs":["PMC"],"master":"Shrug"},
{"name":"Cable Front Raise","muscle":"Shoulders","programs":["Daily Pump"],"master":"Front Raise"},
{"name":"Side Lateral Raise (Cable)","muscle":"Shoulders","programs":["PMC","Daily Pump"],"master":"Side Lateral Raise"},
{"name":"Cable Rope Front Raises","muscle":"Shoulders","programs":["STNDR"],"master":"Front Raise"},
{"name":"Cable Shoulder Press (single arm)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shoulder Press"},
{"name":"Shrug (Cable)","muscle":"Shoulders","programs":["PMC","Daily Pump"],"master":"Shrug"},
{"name":"Cable Shrug (close V grip)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shrug"},
{"name":"Close Grip Barbell Shrug","muscle":"Shoulders","programs":["PMC"],"master":"Shrug"},
{"name":"DB Alternating Press","muscle":"Shoulders","programs":["MC"],"master":"Shoulder Press"},
{"name":"DB Military Press","muscle":"Shoulders","programs":["Daily Pump","PMC","PSU Football"],"master":"Shoulder Press"},
{"name":"Side Lateral Raise (Seated)","muscle":"Shoulders","programs":["Daily Pump","PMC","MC"],"master":"Side Lateral Raise"},
{"name":"Lying Cable Shoulder Press","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shoulder Press"},
{"name":"Machine Shoulder Press","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shoulder Press"},
{"name":"Machine Shrug","muscle":"Shoulders","programs":["Daily Pump","PMC"],"master":"Shrug"},
{"name":"Machine Side Lateral","muscle":"Shoulders","programs":["Daily Pump"],"master":"Side Lateral Raise"},
{"name":"Reverse Machine Shoulder Press","muscle":"Shoulders","programs":["Daily Pump"],"master":"Rear Delt Fly"},
{"name":"Seated Alternating DB Raises","muscle":"Shoulders","programs":["PMC"],"master":"Side Lateral Raise"},
{"name":"Seated Arnold Press","muscle":"Shoulders","programs":["Daily Pump"],"master":"Arnold Press"},
{"name":"Shoulder (Seated)","muscle":"Shoulders","programs":["Daily Pump","STNDR"],"master":"Shoulder Press"},
{"name":"Seated Cable Shoulder Press","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shoulder Press"},
{"name":"Shrug (Seated)","muscle":"Shoulders","programs":["PMC","Daily Pump"],"master":"Shrug"},
{"name":"Front Raise (Seated)","muscle":"Shoulders","programs":["Daily Pump","MC"],"master":"Front Raise"},
{"name":"Seated Double Arm DB Side Lateral (hammer grip)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Side Lateral Raise"},
{"name":"Shoulder (Seated, Hammer)","muscle":"Shoulders","programs":["STNDR","Daily Pump"],"master":"Shoulder Press"},
{"name":"Seated Machine Shoulder Press","muscle":"Shoulders","programs":["Daily Pump","STNDR"],"master":"Shoulder Press"},
{"name":"Seated Rope Front Raises","muscle":"Shoulders","programs":["Daily Pump"],"master":"Front Raise"},
{"name":"Side Lateral Raise (Cable, Single Arm)","muscle":"Shoulders","programs":["STNDR","Daily Pump"],"master":"Side Lateral Raise"},
{"name":"Single Arm Cable Shrug","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shrug"},
{"name":"Smith Machine Shoulder Press","muscle":"Shoulders","programs":["STNDR"],"master":"Shoulder Press"},
{"name":"Shrug (Smith)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Shrug"},
{"name":"Standing Arnold Press","muscle":"Shoulders","programs":["Daily Pump"],"master":"Arnold Press"},
{"name":"Front Raise (Standing)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Front Raise"},
{"name":"Side Lateral Raise (Standing)","muscle":"Shoulders","programs":["STNDR","Daily Pump"],"master":"Side Lateral Raise"},
{"name":"Shrug (Standing)","muscle":"Shoulders","programs":["PMC","Daily Pump"],"master":"Shrug"},
{"name":"Standing Dumbbell Side Lateral (hammer grip)","muscle":"Shoulders","programs":["Daily Pump"],"master":"Side Lateral Raise"},
{"name":"Standing Reverse Delt Cable Flies","muscle":"Shoulders","programs":["PMC"],"master":"Rear Delt Fly"},
{"name":"Underhand Barbell Front Raises","muscle":"Shoulders","programs":["STNDR"],"master":"Front Raise"},
{"name":"Cable Tricep Crossover","muscle":"Triceps","programs":["PMC"],"master":"Lying Tricep Extension"},
{"name":"Lying Tricep Extension (Lying)","muscle":"Triceps","programs":["PMC","MC"],"master":"Lying Tricep Extension"},
{"name":"Double Arm DB Tricep Extensions","muscle":"Triceps","programs":["Daily Pump","MC","Strength & Supersets"],"master":"Lying Tricep Extension"},
{"name":"Diamond Pushups","muscle":"Triceps","programs":["Daily Pump"],"master":null},
{"name":"Overhead DB Extension (two hands)","muscle":"Triceps","programs":["Daily Pump"],"master":"Overhead Tricep Extension"},
{"name":"Double Arm Overhead Pin Rack Extensions","muscle":"Triceps","programs":["Daily Pump"],"master":"Overhead Tricep Extension"},
{"name":"Overhead Tricep Extension (Cable)","muscle":"Triceps","programs":["PMC","Daily Pump"],"master":"Overhead Tricep Extension"},
{"name":"Floor Skull Crushers (hands touching)","muscle":"Triceps","programs":["Daily Pump"],"master":"Skull Crusher"},
{"name":"French Press","muscle":"Triceps","programs":["PMC","Strength & Supersets"],"master":null},
{"name":"Lying Single Arm Tricep Extension","muscle":"Triceps","programs":["PMC"],"master":"Lying Tricep Extension"},
{"name":"Overhead Tricep Extension (cable rope)","muscle":"Triceps","programs":["Daily Pump"],"master":"Overhead Tricep Extension"},
{"name":"Overhead Tricep Extension (Rope)","muscle":"Triceps","programs":["STNDR","PMC"],"master":"Overhead Tricep Extension"},
{"name":"Pushups","muscle":"Triceps","programs":["Daily Pump"],"master":null},
{"name":"Quad Extension","muscle":"Triceps","programs":["PMC","MC","Strength & Supersets"],"master":"Quad Extension"},
{"name":"Quad Extensions (AMRAP)","muscle":"Triceps","programs":["MC"],"master":"Quad Extension"},
{"name":"Reverse Tricep Pushdowns","muscle":"Triceps","programs":["MC"],"master":"Tricep Pushdown"},
{"name":"Tricep Pushdown (Rope)","muscle":"Triceps","programs":["Daily Pump","MC","PMC","STNDR"],"master":"Tricep Pushdown"},
{"name":"Seated Double Arm Dumbbell Kick Back","muscle":"Triceps","programs":["Daily Pump"],"master":"Tricep Kickback"},
{"name":"Overhead Tricep Extension (Seated)","muscle":"Triceps","programs":["Daily Pump","MC"],"master":"Overhead Tricep Extension"},
{"name":"Seated Overhead EZ Bar Tricep Extension","muscle":"Triceps","programs":["STNDR"],"master":"Overhead Tricep Extension"},
{"name":"Seated Overhead Tricep Cable Extension","muscle":"Triceps","programs":["STNDR"],"master":"Overhead Tricep Extension"},
{"name":"Single Arm Cross Body Tricep Extension","muscle":"Triceps","programs":["STNDR"],"master":"Lying Tricep Extension"},
{"name":"Single Arm Overhead Cable Extension","muscle":"Triceps","programs":["STNDR"],"master":"Overhead Tricep Extension"},
{"name":"Single Arm Overhead Extension","muscle":"Triceps","programs":["Daily Pump"],"master":"Overhead Tricep Extension"},
{"name":"Tricep Pushdown (Single Arm)","muscle":"Triceps","programs":["STNDR","Daily Pump"],"master":"Tricep Pushdown"},
{"name":"Skull Crushers (EZ bar)","muscle":"Triceps","programs":["Daily Pump"],"master":"Skull Crusher"},
{"name":"Slight Incline Skull Crushers","muscle":"Triceps","programs":["PMC"],"master":"Skull Crusher"},
{"name":"Standing Double Arm Cable Kick Outs","muscle":"Triceps","programs":["Daily Pump"],"master":"Tricep Kickback"},
{"name":"Standing Double Arm DB Extension","muscle":"Triceps","programs":["Daily Pump"],"master":"Overhead Tricep Extension"},
{"name":"Tricep Pushdown (Cable)","muscle":"Triceps","programs":["STNDR","Daily Pump"],"master":"Tricep Pushdown"},
{"name":"Tricep","muscle":"Triceps","programs":["PSU Football","Daily Pump"],"master":"Tricep Machine"},
{"name":"Tricep Cable Press Down (rope)","muscle":"Triceps","programs":["Daily Pump"],"master":"Tricep Pushdown"},
{"name":"Tricep Pushdown","muscle":"Triceps","programs":["MC","PMC","STNDR","Daily Pump"],"master":"Tricep Pushdown"},
{"name":"100-Rep Barbell Bench","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"1–18 Push-up Ladder","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Alternating DB Incline Skullcrushers","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Alternating DB Slight Incline Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Alternating Slight Incline Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Alternating Standing DB Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Barbell Flat Bench","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Barbell Floor Skullcrushers","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Barbell Military Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Barbell Pendlay Row","muscle":"Back","programs":["Strength & Supersets"],"master":"Barbell Pendlay Row"},
{"name":"Barbell Pendlay Row (Snatch Grip)","muscle":"Back","programs":["Strength & Supersets"],"master":"Barbell Pendlay Row"},
{"name":"Barbell RDLs","muscle":"Legs - Hamstrings","programs":["Strength & Supersets"],"master":null},
{"name":"Barbell Spider Curls","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Barbell Split Squat","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":null},
{"name":"Barbell Squat (shoulder width)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Barbell Squat"},
{"name":"Barbell Squat (sumo stance)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Barbell Squat"},
{"name":"Barbell Walking Lunges","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":null},
{"name":"Behind-the-Back Barbell Curls","muscle":"Forearms","programs":["Strength & Supersets"],"master":null},
{"name":"Bicep Cable Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Bicep Curl (hands touching)","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Cable Crossover","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Cable Overhead Extension","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Cable Rope Straight-Arm Pulldown","muscle":"Back","programs":["Strength & Supersets"],"master":null},
{"name":"Close-Grip Barbell Bench","muscle":"Triceps","programs":["Strength & Supersets"],"master":"Underhand Barbell Bench"},
{"name":"Close-Grip Bench Press","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Close-Grip Lat Pulldown","muscle":"Back","programs":["Strength & Supersets"],"master":"Lat Pulldown"},
{"name":"Cross-Body DB Tricep Extension","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"DB Arnold Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"DB Floor Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"DB Goblet Squat (heels elevated, feet together)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"DB Sumo Goblet Squats"},
{"name":"DB Goblet Squats (neutral stance)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"DB Sumo Goblet Squats"},
{"name":"DB Holds","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"DB Lateral Raise","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"DB Seated Shoulder Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"DB Shoulder Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"DB Step-ups","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":null},
{"name":"DB Sumo Goblet Squats","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"DB Sumo Goblet Squats"},
{"name":"Deadlift","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":null},
{"name":"Decline Cable Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Diamond Push-ups","muscle":"Chest","programs":["Strength & Supersets"],"master":"Diamond Pushups"},
{"name":"Donkey Calf Raise","muscle":"Calves","programs":["Strength & Supersets"],"master":"Donkey Calf Raise"},
{"name":"Donkey Calf Raise — High Volume","muscle":"Calves","programs":["Strength & Supersets"],"master":"Donkey Calf Raise"},
{"name":"Double-Arm DB Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Double-Arm Kneeling Wrist Curl","muscle":"Forearms","programs":["Strength & Supersets"],"master":null},
{"name":"Flat Bench DB Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":"Flat Bench DB Flies"},
{"name":"Flat Bench DB Press (hands touching)","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Flat DB Hammer Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Floor Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Fly to Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Goblet Squat (feet touching, heels elevated)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Goblet Squat"},
{"name":"Hack Squat (feet together)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Hack Squat"},
{"name":"Hack Squat (feet touching, feet low)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Hack Squat"},
{"name":"Hack Squat (neutral stance)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Hack Squat"},
{"name":"Hack Squat (shoulder width)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Hack Squat"},
{"name":"Hammer Strength Shoulder Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"High Incline Hammer Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Hip Thrust","muscle":"Legs - Glutes","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Alternating DB Curls","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Barbell Bench","muscle":"Chest","programs":["Strength & Supersets"],"master":"Incline Barbell Bench"},
{"name":"Incline Barbell Bench (1½ reps)","muscle":"Chest","programs":["Strength & Supersets"],"master":"Incline Barbell Bench"},
{"name":"Incline Barbell Bench (2 sec pause)","muscle":"Chest","programs":["Strength & Supersets"],"master":"Incline Barbell Bench"},
{"name":"Incline Barbell Face Pull","muscle":"Back","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Barbell Front Raise","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Cable Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Chest-Supported DB Row","muscle":"Back","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Double-Arm Bicep Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Machine Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Incline Smith Machine Bench","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Inner Thigh (Adductor)","muscle":"Adductors","programs":["Strength & Supersets"],"master":null},
{"name":"JM Press","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Kneeling Barbell Wrist Curl (wide grip)","muscle":"Forearms","programs":["Strength & Supersets"],"master":null},
{"name":"Kneeling Reverse Barbell Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Kneeling Single-Arm DB Forearm Curl","muscle":"Forearms","programs":["Strength & Supersets"],"master":null},
{"name":"Lat Pulldown (Underhand Grip)","muscle":"Back","programs":["Strength & Supersets"],"master":"Lat Pulldown"},
{"name":"Leg Press (feet touching)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Leg Press"},
{"name":"Leg Press (high & wide)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Leg Press"},
{"name":"Leg Press (medium stance)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Leg Press"},
{"name":"Leg Press Calf Raise","muscle":"Calves","programs":["Strength & Supersets"],"master":"Leg Press Calf Raise"},
{"name":"Leg Press Calf Raise — High Volume","muscle":"Calves","programs":["Strength & Supersets"],"master":"Leg Press Calf Raise"},
{"name":"Leg Press Calf Raises","muscle":"Calves","programs":["Strength & Supersets"],"master":"Leg Press Calf Raise"},
{"name":"Leg Press Calf Raises (toes pointed out)","muscle":"Calves","programs":["Strength & Supersets"],"master":"Leg Press Calf Raise"},
{"name":"Lying Hamstring Curls","muscle":"Legs - Hamstrings","programs":["Strength & Supersets"],"master":null},
{"name":"Machine Preacher Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":"Machine Preacher Curl"},
{"name":"Outer Thigh (Abductor)","muscle":"Legs - Glutes","programs":["Strength & Supersets"],"master":null},
{"name":"Peck Deck Flies (2 sec pause)","muscle":"Chest","programs":["Strength & Supersets"],"master":"Pronated Peck Deck Flies"},
{"name":"Pelican Raise","muscle":"Back","programs":["Strength & Supersets"],"master":null},
{"name":"Preacher Curl (hammer grip)","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Pronated DB Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Pronated Flat Bench DB Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":"Flat Bench DB Flies"},
{"name":"Pronated Peck Deck Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":"Pronated Peck Deck Flies"},
{"name":"Pull-Up","muscle":"Back","programs":["Strength & Supersets"],"master":"Pull-Up"},
{"name":"Push-ups","muscle":"Chest","programs":["Strength & Supersets"],"master":"Pushups"},
{"name":"Quad Extension Burnout","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":null},
{"name":"Reverse Barbell Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Reverse Cable Fly","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Reverse Incline DB Fly","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Reverse Kneeling Wrist Curl","muscle":"Forearms","programs":["Strength & Supersets"],"master":null},
{"name":"Reverse Pec Deck Fly","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Rope Cable Hammer Curls","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Seated Alternating DB Lateral Raise","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Seated DB Lateral Raise","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Side Lateral to Front Raise","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Single DB Sumo RDLs","muscle":"Legs - Hamstrings","programs":["Strength & Supersets"],"master":null},
{"name":"Single Leg Quad Extensions","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm Cable Lateral Raise","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm DB Lateral Raise","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm DB Lawnmower Row","muscle":"Back","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm DB Skullcrushers","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm Overhead Tricep Extension","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm Smith Machine Shrug","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm Tricep Cable Extension","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Arm Tricep Kickback","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Single-Leg DB Calf Raise","muscle":"Calves","programs":["Strength & Supersets"],"master":null},
{"name":"Skull Crushers","muscle":"Triceps","programs":["Strength & Supersets"],"master":"Skull Crusher"},
{"name":"Slight Incline DB Bench","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Slight Incline DB Flies","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Slight Incline DB Press","muscle":"Chest","programs":["Strength & Supersets"],"master":"Incline DB Press"},
{"name":"Slight Incline Fly to Press","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Slight Incline Skullcrushers","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine Behind-the-Back Wrist Curls","muscle":"Forearms","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine Bench (1½ reps)","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine Bent-Over Row","muscle":"Back","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine Calf Raise (toes out)","muscle":"Calves","programs":["Strength & Supersets"],"master":"Smith Machine Calf Raise"},
{"name":"Smith Machine Calf Raise (toes out) — High Volume","muscle":"Calves","programs":["Strength & Supersets"],"master":"Smith Machine Calf Raise"},
{"name":"Smith Machine Calf Raises (toes pointed out)","muscle":"Calves","programs":["Strength & Supersets"],"master":"Smith Machine Calf Raise"},
{"name":"Smith Machine Flat Bench (1½ reps)","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine Military Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine RDLs","muscle":"Legs - Hamstrings","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine Skullcrushers","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Smith Machine Squat (heel elevated, feet together)","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":"Smith Machine Squat (Smith)"},
{"name":"Smith Machine Upright Row","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Spider Curl","muscle":"Biceps","programs":["Strength & Supersets"],"master":"Spider Curl"},
{"name":"Spider Curl (gauntlet set)","muscle":"Biceps","programs":["Strength & Supersets"],"master":"Spider Curl"},
{"name":"Standing Barbell Pin Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Standing Calf Raise (Machine)","muscle":"Calves","programs":["Strength & Supersets"],"master":null},
{"name":"Standing Double-Arm Hammer Curls","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Standing Overhead Barbell Press","muscle":"Shoulders","programs":["Strength & Supersets"],"master":null},
{"name":"Strict Barbell Curl (wall-supported)","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Tricep Gauntlet","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Tricep Pushdowns (rope)","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Underhand Barbell Bench","muscle":"Chest","programs":["Strength & Supersets"],"master":"Underhand Barbell Bench"},
{"name":"Walking Lunges","muscle":"Legs - Quads","programs":["Strength & Supersets"],"master":null},
{"name":"Weighted Dips","muscle":"Triceps","programs":["Strength & Supersets"],"master":null},
{"name":"Weighted Push-ups","muscle":"Chest","programs":["Strength & Supersets"],"master":null},
{"name":"Wide-Grip Barbell Shrug","muscle":"Shoulders","programs":["Strength & Supersets"],"master":"Barbell Snatch Shrug"},
{"name":"Wide-Grip Lat Pulldown","muscle":"Back","programs":["Strength & Supersets"],"master":"Lat Pulldown"},
{"name":"Wrist Rolls","muscle":"Forearms","programs":["Strength & Supersets"],"master":null},
{"name":"Zottman Curls","muscle":"Biceps","programs":["Strength & Supersets"],"master":null},
{"name":"Ballistic Row","muscle":"Back","programs":[],"master":null},
{"name":"Barbell Pullover","muscle":"Back","programs":[],"master":null},
{"name":"Chin Ups","muscle":"Back","programs":[],"master":null},
{"name":"Meadows Row","muscle":"Back","programs":[],"master":null},
{"name":"Pendlay Row","muscle":"Back","programs":[],"master":null},
{"name":"Rope Pullover","muscle":"Back","programs":[],"master":null},
{"name":"Hammer Strength Low Row","muscle":"Back","programs":[],"master":null},
{"name":"Rack Chins on Smith Machine","muscle":"Back","programs":[],"master":null},
{"name":"Barbell Bench Press","muscle":"Chest","programs":[],"master":null},
{"name":"Pec Deck","muscle":"Chest","programs":[],"master":null},
{"name":"DB Fly to Press","muscle":"Chest","programs":[],"master":null},
{"name":"Cable Machine Press","muscle":"Chest","programs":[],"master":null},
{"name":"Flat Chest Press Machine","muscle":"Chest","programs":[],"master":null},
{"name":"Smith Machine Incline Press","muscle":"Chest","programs":[],"master":null},
{"name":"Flat Smith Machine Press","muscle":"Chest","programs":[],"master":null},
{"name":"Hammer Strength Decline Press","muscle":"Chest","programs":[],"master":null},
{"name":"High Incline Smith Machine Press","muscle":"Chest","programs":[],"master":null},
{"name":"Single Arm Hammer Strength Incline","muscle":"Chest","programs":[],"master":null},
{"name":"Low Pulley Cable Cross Over","muscle":"Chest","programs":[],"master":null},
{"name":"2 Arm Standing Overhead Press","muscle":"Shoulders","programs":[],"master":null},
{"name":"Barbell Front Raise","muscle":"Shoulders","programs":[],"master":null},
{"name":"Machine Overhead Press","muscle":"Shoulders","programs":[],"master":null},
{"name":"Standing Push Press","muscle":"Shoulders","programs":[],"master":null},
{"name":"Standing Single Arm Overhead Press","muscle":"Shoulders","programs":[],"master":null},
{"name":"Sots Press","muscle":"Shoulders","programs":[],"master":null},
{"name":"Chest-Supported Side Lateral Raises","muscle":"Shoulders","programs":[],"master":null},
{"name":"Rope Upright Row","muscle":"Shoulders","programs":[],"master":null},
{"name":"Hammer Strength Military Press","muscle":"Shoulders","programs":[],"master":null},
{"name":"2 Arm DB Hammer Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"Cable Barbell Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"Close Grip Cable EZ Bar Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"Wide Grip Cable EZ Bar Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"Reverse Grip Cable EZ Bar Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"EZ Bar Preacher Curls","muscle":"Biceps","programs":[],"master":null},
{"name":"Close Grip EZ Bar Preacher Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"Reverse Grip EZ Bar Preacher Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"Front Double Bicep Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"Single Arm Rope Hammer Curl","muscle":"Biceps","programs":[],"master":null},
{"name":"2 Arm DB Kickback","muscle":"Triceps","programs":[],"master":null},
{"name":"DB Kickback","muscle":"Triceps","programs":[],"master":null},
{"name":"Dead Skulls","muscle":"Triceps","programs":[],"master":null},
{"name":"Rope Extension","muscle":"Triceps","programs":[],"master":null},
{"name":"Seated EZ Bar Overhead Extension","muscle":"Triceps","programs":[],"master":null},
{"name":"Tate Press","muscle":"Triceps","programs":[],"master":null},
{"name":"Barbell Skullcrushers","muscle":"Triceps","programs":[],"master":null},
{"name":"Barbell Hack Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Narrow Stance Hack Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Bulgarian Split Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Bodyweight Squats","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Bodyweight Lunges","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Stationary Lunges","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Reverse Lunge","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Overhead Lunge","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Close Stance Leg Press","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"High & Wide Stance Leg Press","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Front Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Overhead Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Jefferson Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Zercher Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Pistol Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Step Up","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Step Up with Knee Raise","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"Jump Squat","muscle":"Legs - Quads","programs":[],"master":null},
{"name":"DB Stiff Leg Deadlift","muscle":"Legs - Hamstrings","programs":[],"master":null},
{"name":"Good Morning","muscle":"Legs - Hamstrings","programs":[],"master":null},
{"name":"Donkey Kicks","muscle":"Legs - Glutes","programs":[],"master":null},
{"name":"Glute Bridge","muscle":"Legs - Glutes","programs":[],"master":null},
{"name":"Single Leg Glute Bridge","muscle":"Legs - Glutes","programs":[],"master":null},
{"name":"Calf Press on Leg Press","muscle":"Calves","programs":[],"master":null},
{"name":"Ab Wheel","muscle":"Core","programs":[],"master":null},
{"name":"Fingertip Plank","muscle":"Core","programs":[],"master":null},
{"name":"Incline Sit Up","muscle":"Core","programs":[],"master":null},
{"name":"V-Sit","muscle":"Core","programs":[],"master":null},
{"name":"Towel Hang Leg Raise","muscle":"Core","programs":[],"master":null},
{"name":"DB Wrist Curl","muscle":"Forearms","programs":[],"master":null},
{"name":"Plate Pinch","muscle":"Forearms","programs":[],"master":null},
{"name":"Towel Hangs","muscle":"Forearms","programs":[],"master":null},
{"name":"Elliptical","muscle":"Cardio","programs":[],"master":null},
{"name":"Stairmaster","muscle":"Cardio","programs":[],"master":null},
{"name":"Stationary Bike","muscle":"Cardio","programs":[],"master":null},
{"name":"Incline Treadmill","muscle":"Cardio","programs":[],"master":null},
{"name":"Rower Machine","muscle":"Cardio","programs":[],"master":null},
{"name":"Standing Long Jump","muscle":"Cardio","programs":[],"master":null},
{"name":"Sprints","muscle":"Cardio","programs":[],"master":null},
{"name":"Turkish Get Up","muscle":"Full Body","programs":[],"master":null},
{"name":"Spider Crawl","muscle":"Full Body","programs":[],"master":null},
];
var MUSCLE_COLORS={"Back":"#22d3ee","Chest":"#f472b6","Shoulders":"#60a5fa","Biceps":"#a78bfa","Triceps":"#fb923c","Legs - Quads":"#4ade80","Legs - Hamstrings":"#34d399","Legs - Glutes":"#86efac","Calves":"#fde68a","Core":"#f87171","Forearms":"#94a3b8","Cardio":"#f59e0b","Full Body":"#e879f9","Adductors":"#67e8f9"};
var MUSCLE_ICONS={"Back":"&#128281;","Chest":"&#129521;","Shoulders":"&#127956;","Biceps":"&#128170;","Triceps":"&#128165;","Legs - Quads":"&#129461;","Legs - Hamstrings":"&#127825;","Legs - Glutes":"&#127825;","Calves":"&#129462;","Core":"&#128293;","Forearms":"&#128295;","Cardio":"&#127939;","Full Body":"&#9889;","Adductors":"&#8592;"};
window.EXERCISES=EXERCISES;window.MUSCLE_COLORS=MUSCLE_COLORS;window.MUSCLE_ICONS=MUSCLE_ICONS;
