/* mc-db.js  --  MC Training client-side data layer (static PWA)
 *
 * Generated by 1-infra-deploy.py. Defines the app "schema":
 *   - user/profile (client-side auth scaffold)
 *   - workout history log  (immutable transaction table)
 *   - replacement log      (session-scoped exercise swaps)
 *
 * GLOBAL RULE: replacements are recorded as transactions in the history/
 * replacement logs and MUST NOT overwrite master program/split definitions
 * (those live in the static workout HTML files and are always the source of
 * truth). Re-opening a program always shows the original exercises.
 */
(function (global) {
  "use strict";

  var KEYS = {
    USER: "mc_user",            // { id, name, createdAt }
    HISTORY: "mc_history",      // [ completedWorkout, ... ]   append-only
    REPLACEMENTS: "mc_replace_log" // [ replacementTxn, ... ]  append-only
  };

  function read(key, fallback) {
    try { return JSON.parse(global.localStorage.getItem(key)) || fallback; }
    catch (e) { return fallback; }
  }
  function write(key, value) {
    global.localStorage.setItem(key, JSON.stringify(value));
  }
  function uid() {
    return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
  }

  /* ---- User / auth (client-side scaffold) ---- */
  var Auth = {
    getUser: function () { return read(KEYS.USER, null); },
    signIn: function (name) {
      var u = { id: uid(), name: name || "Athlete", createdAt: Date.now() };
      write(KEYS.USER, u);
      return u;
    },
    signOut: function () { global.localStorage.removeItem(KEYS.USER); }
  };

  /* ---- Workout history (transaction log; never mutates programs) ---- */
  var History = {
    all: function () { return read(KEYS.HISTORY, []); },
    /* entry: { program, workout, exercises:[...], replacements:[...] } */
    log: function (entry) {
      var log = read(KEYS.HISTORY, []);
      var rec = {
        id: uid(),
        ts: Date.now(),
        program: entry.program || "",
        workout: entry.workout || "",
        exercises: entry.exercises || [],
        replacements: entry.replacements || []
      };
      log.push(rec);
      write(KEYS.HISTORY, log);
      return rec;
    },
    clear: function () { write(KEYS.HISTORY, []); }
  };

  /* ---- Replacement transactions (session-scoped, non-permanent) ----
   * A replacement applies ONLY to the active workout session it was made in.
   * It is logged for history but is NOT written back to the master program,
   * so it never carries over to other workouts or programs.
   */
  var Replacements = {
    all: function () { return read(KEYS.REPLACEMENTS, []); },
    /* record a swap made during a live session */
    record: function (sessionId, workout, original, replacement) {
      var log = read(KEYS.REPLACEMENTS, []);
      var txn = {
        id: uid(),
        sessionId: sessionId,
        workout: workout || "",
        original: original,
        replacement: replacement,
        ts: Date.now()
      };
      log.push(txn);
      write(KEYS.REPLACEMENTS, log);
      return txn;
    },
    /* swaps for a single live session (used to render the active workout) */
    forSession: function (sessionId) {
      return read(KEYS.REPLACEMENTS, []).filter(function (t) {
        return t.sessionId === sessionId;
      });
    }
  };

  global.MC_DB = {
    KEYS: KEYS,
    Auth: Auth,
    History: History,
    Replacements: Replacements,
    newSession: uid
  };
})(typeof window !== "undefined" ? window : this);
