// MC Training — Service Worker v2
// Relative-path precache so the app works at any GitHub Pages project subpath

const CACHE_NAME = 'mc-training-market-ci-31';
const BASE = 'https://mcross2298.github.io/MC-Training-Rolodex/';
// The list below is generated by tools/build-sw.py — do not edit by hand.
const CACHE_URLS = [
    /* AUTOGEN:URLS START */
    './',
    './45-minute-burner.html',
    './base.css',
    './battle-ropes.html',
    './bonus-workouts.html',
    './boxing-routine.html',
    './build-program.html',
    './build-workout.html',
    './cat-custom.html',
    './cat-faint.html',
    './cat-mc.html',
    './cat-pmc.html',
    './cat-strength.html',
    './collections.html',
    './conditioning-data.js',
    './conditioning-elite.css',
    './conditioning-timer.html',
    './dashboard.html',
    './driveway-demolition.html',
    './exercise-catalog.js',
    './exercise-library.html',
    './exercisedata.json',
    './faint-instructions.html',
    './full-body-pyramid.html',
    './hell-week.html',
    './icon.svg',
    './import.html',
    './index.html',
    './manifest.json',
    './max-out.html',
    './mc-account.js',
    './mc-backup-status.js',
    './mc-biometric.js',
    './mc-body.js',
    './mc-bonus-routing.js',
    './mc-card-actions.css',
    './mc-card-actions.js',
    './mc-cardio.html',
    './mc-chart.js',
    './mc-collections.js',
    './mc-cond.js',
    './mc-cues-data.js',
    './mc-cues.js',
    './mc-exercise-catalog.js',
    './mc-exercise-trends.js',
    './mc-finish.js',
    './mc-group-split.js',
    './mc-home.html',
    './mc-instructions.html',
    './mc-interval.js',
    './mc-layout.js',
    './mc-live-tracker.js',
    './mc-maxout.js',
    './mc-muscle-map.js',
    './mc-naming-paint.js',
    './mc-naming.js',
    './mc-nav.css',
    './mc-nav.js',
    './mc-pm-creator.js',
    './mc-pm-data.js',
    './mc-pm-layout-editor.js',
    './mc-program-builder.js',
    './mc-program-pub.js',
    './mc-program-store.js',
    './mc-recap.js',
    './mc-rep-progress.js',
    './mc-replace.js',
    './mc-reps.js',
    './mc-resume.js',
    './mc-s1-back.html',
    './mc-s1-bis-tris.html',
    './mc-s1-chest-shoulders.html',
    './mc-s1-legs.html',
    './mc-s1-legs2.html',
    './mc-s2-back.html',
    './mc-s2-chest-bis.html',
    './mc-s2-cst.html',
    './mc-s2-legs.html',
    './mc-s2-legs2.html',
    './mc-s3-back-bis-forearms.html',
    './mc-s3-back.html',
    './mc-s3-chest.html',
    './mc-s3-legs-back.html',
    './mc-s3-legs.html',
    './mc-s3-shoulders-tris.html',
    './mc-s4-bis-tris.html',
    './mc-s4-chest-tris.html',
    './mc-s4-legs.html',
    './mc-s4-shoulders.html',
    './mc-s5-legs.html',
    './mc-s5-pull.html',
    './mc-s5-push.html',
    './mc-session.js',
    './mc-setlog.css',
    './mc-setlog.js',
    './mc-share.js',
    './mc-split1.html',
    './mc-split2.html',
    './mc-split3.html',
    './mc-split4.html',
    './mc-split5.html',
    './mc-stats.js',
    './mc-suggest.js',
    './mc-summary.css',
    './mc-summary.js',
    './mc-supabase.js',
    './mc-superset-hop.js',
    './mc-sw-update.js',
    './mc-sync.js',
    './mc-theme.js',
    './mc-timer.js',
    './mc-wrapped.js',
    './mcdb.js',
    './pm-mode-overview.html',
    './pmc-back.html',
    './pmc-bis-tris.html',
    './pmc-chest-shoulders.html',
    './pmc-data.js',
    './pmc-home.html',
    './pmc-instructions.html',
    './pmc-legs-hams.html',
    './pmc-legs-quad.html',
    './pmc-s2-back.html',
    './pmc-s2-chest-biceps.html',
    './pmc-s2-cst.html',
    './pmc-s2-legs-day2.html',
    './pmc-s2-legs-quad.html',
    './pmc-s3-back-bis-forearms.html',
    './pmc-s3-back.html',
    './pmc-s3-chest.html',
    './pmc-s3-legs.html',
    './pmc-s3-shoulders-tris.html',
    './pmc-s4-bis-tris.html',
    './pmc-s4-chest-tris.html',
    './pmc-s4-legs-back.html',
    './pmc-s4-legs-day2.html',
    './pmc-s4-shoulders.html',
    './pmc-s5-core.html',
    './pmc-s5-legs.html',
    './pmc-s5-pull.html',
    './pmc-s5-push.html',
    './pmc-s6-abs-circuit.html',
    './pmc-s6-back-traps.html',
    './pmc-s6-chest.html',
    './pmc-s6-delts-arms.html',
    './pmc-s6-legs.html',
    './pmc-s7-data.js',
    './pmc-s7-giant.html',
    './pmc-split1.html',
    './pmc-split2.html',
    './pmc-split3.html',
    './pmc-split4.html',
    './pmc-split5.html',
    './pmc-split6.html',
    './pmc-split7.html',
    './pmc-workout.html',
    './popeye.html',
    './program-guide.html',
    './program-manager.js',
    './program-overrides.js',
    './program-overrides.json',
    './quick-tour-overview.html',
    './quick-tour.html',
    './run-program.html',
    './run-workout.html',
    './stats.html',
    './superset-timers.js',
    './sw.js',
    './the-500.html',
    './turn-and-burn.html',
    './workout-logs.html',
    './wrapped.html'
    /* AUTOGEN:URLS END */
];

// Install — cache everything
self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {
            console.log('[SW] Caching', CACHE_URLS.length, 'files');
            // Cache in batches to avoid timeout
            const batch = (arr, size) => Array.from({length:Math.ceil(arr.length/size)}, (_,i) => arr.slice(i*size,i*size+size));
            const batches = batch(CACHE_URLS, 20);
            return batches.reduce((p, b) => p.then(() =>
                Promise.allSettled(b.map(u => cache.add(u).catch(err => console.log('[SW] Cache miss:', u, err))))
            ), Promise.resolve());
        })
    );
    self.skipWaiting();
});

// Activate — remove ALL old caches, take control, and force-reload every open
// tab so stale pages held by a previous worker are replaced immediately.
self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys()
            .then(keys => Promise.all(
                keys.filter(k => k !== CACHE_NAME).map(k => {
                    console.log('[SW] Removing old cache:', k);
                    return caches.delete(k);
                })
            ))
            .then(() => self.clients.claim())
            .then(() => self.clients.matchAll({ type: 'window' }))
            .then(clients => clients.forEach(c => {
                // Reload each controlled tab once so it picks up fresh files.
                try { c.navigate(c.url); } catch (e) {}
            }))
    );
});

// Fetch — HTML: network-only (always fresh). CSS/JS/assets: network-first with cache fallback.
self.addEventListener('fetch', event => {
    const url = event.request.url;

    // Only handle requests to our domain
    if (!url.startsWith('https://mcross2298.github.io')) return;

    // HTML files must always be fresh — never serve from cache
    const isHTML = url.endsWith('.html') || url.endsWith('/') || !url.split('/').pop().includes('.');
    if (isHTML) {
        event.respondWith(
            fetch(event.request).catch(() => {
                return caches.match(event.request).then(cached => cached || new Response(
                    '<html><body style="background:#0a0a0a;color:#fff;font-family:sans-serif;text-align:center;padding:60px 20px"><h2 style="color:#d4af37">MC Training</h2><p style="color:#9ca3af;margin-top:12px">You are offline.</p><a href="/" style="display:inline-block;margin-top:20px;color:#d4af37">← Home</a></body></html>',
                    {headers: {'Content-Type': 'text/html'}}
                ));
            })
        );
        return;
    }

    // CSS/JS/assets: network-first, cache fallback
    event.respondWith(
        fetch(event.request).then(resp => {
            if (resp && resp.status === 200) {
                const clone = resp.clone();
                caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
            }
            return resp;
        }).catch(() => {
            return caches.match(event.request).then(cached => {
                if (cached) return cached;
                return new Response(
                    '<html><body style="background:#0a0a0a;color:#fff;font-family:sans-serif;text-align:center;padding:60px 20px"><h2 style="color:#d4af37">MC Training</h2><p style="color:#9ca3af;margin-top:12px">You are offline. Open this page while online to cache it.</p><a href="/" style="display:inline-block;margin-top:20px;color:#d4af37">← Home</a></body></html>',
                    {headers: {'Content-Type': 'text/html'}}
                );
            });
        })
    );
});

// Message — force update
self.addEventListener('message', event => {
    if (event.data === 'skipWaiting') self.skipWaiting();
});