// MC Training — Service Worker v2
// Relative-path precache so the app works at any GitHub Pages project subpath

const CACHE_NAME = 'mc-training-market-ci-269';
const BASE = 'https://mcross2298.github.io/MC-Training-Rolodex/';

// DG-1/DG-2: the app's one type identity (Archivo+Manrope) is loaded from
// Google Fonts on every page now, via tools/apply-head-contract.py's
// FONT_LINK. Cross-origin, so the same-origin-only fetch handler below
// would otherwise never cache it, and the app's whole visual identity would
// vanish offline. Not part of the AUTOGEN precache list above (that globs
// real files in this repo, and the actual .woff2 files Google serves are a
// dynamic, UA-dependent set of URLs — not something safe to hardcode) — a
// SEPARATE, stable cache populated lazily on first real fetch instead, the
// same "network first, cache on success, offline falls back to whatever we
// already have" shape assetOfflinePage() already gives every other asset.
// A stable name (not CACHE_NAME, which bumps every deploy) so a font
// already fetched survives future deploys instead of re-downloading it —
// the font itself doesn't change when this app does.
const FONT_CACHE_NAME = 'mc-training-fonts-v1';
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];
// The list below is generated by tools/build-sw.py — do not edit by hand.
const CACHE_URLS = [
    /* AUTOGEN:URLS START */
    './',
    './apple-touch-icon.png',
    './base.css',
    './conditioning-data.js',
    './dashboard.html',
    './exercise-catalog.js',
    './icon-192-maskable.png',
    './icon-192.png',
    './icon-512-maskable.png',
    './icon-512.png',
    './icon.svg',
    './index.html',
    './ks-engine.js',
    './manifest.json',
    './mc-account.js',
    './mc-appearance.js',
    './mc-backup-status.js',
    './mc-barcode.js',
    './mc-biomech.js',
    './mc-biometric.js',
    './mc-body.js',
    './mc-bonus-routing.js',
    './mc-bridge.js',
    './mc-calendar.js',
    './mc-card-actions.css',
    './mc-card-actions.js',
    './mc-chart.js',
    './mc-collections.js',
    './mc-cond-suggest.js',
    './mc-cond.js',
    './mc-cues-data.js',
    './mc-cues.js',
    './mc-data.js',
    './mc-engine.js',
    './mc-exercise-catalog.js',
    './mc-exercise-trends.js',
    './mc-export.js',
    './mc-finish.js',
    './mc-foodapi.js',
    './mc-freq-engine.js',
    './mc-global-search.js',
    './mc-group-split.js',
    './mc-guided.js',
    './mc-haptics.js',
    './mc-hints.js',
    './mc-input-sheet.js',
    './mc-install.js',
    './mc-interval.js',
    './mc-layout.js',
    './mc-light.css',
    './mc-live-tracker.js',
    './mc-macrocalc.js',
    './mc-macros.js',
    './mc-maxout.js',
    './mc-muscle-map.js',
    './mc-naming-paint.js',
    './mc-naming.js',
    './mc-nav.css',
    './mc-nav.js',
    './mc-offline-prefetch.js',
    './mc-onboarding.js',
    './mc-pm-creator.js',
    './mc-pm-data.js',
    './mc-pm-inline.js',
    './mc-pm-layout-editor.js',
    './mc-pmc-engine.js',
    './mc-program-builder.js',
    './mc-program-hero.css',
    './mc-program-hero.js',
    './mc-program-landing.css',
    './mc-program-pub.js',
    './mc-program-status.js',
    './mc-program-store.js',
    './mc-pump-engine.js',
    './mc-push.js',
    './mc-quick-pump.js',
    './mc-readiness.js',
    './mc-recap.js',
    './mc-rep-progress.js',
    './mc-replace.js',
    './mc-reps.js',
    './mc-resume.js',
    './mc-s3-engine.js',
    './mc-schedule.js',
    './mc-session.js',
    './mc-setlog.css',
    './mc-setlog.js',
    './mc-share.js',
    './mc-stats.js',
    './mc-strain.js',
    './mc-suggest.js',
    './mc-summary.css',
    './mc-summary.js',
    './mc-supabase.js',
    './mc-superset-hop.js',
    './mc-surprise.css',
    './mc-surprise.js',
    './mc-sw-update.js',
    './mc-swap-manager.js',
    './mc-sync.js',
    './mc-theme.js',
    './mc-timer.js',
    './mc-voice.js',
    './mc-workout-engine.js',
    './mc-wrapped.js',
    './mm-data.js',
    './mm-engine.js',
    './pmc-s7-data.js',
    './program-manager.js',
    './program-overrides.js',
    './program-overrides.json',
    './sw.js'
    /* AUTOGEN:URLS END */
];

// Install — cache everything
self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {
            console.log('[SW] Caching', CACHE_URLS.length, 'files');
            // Cache in batches to avoid timeout
            const batch = (arr, size) => Array.from({length:Math.ceil(arr.length/size)}, (_,i) => arr.slice(i*size,i*size+size));
            const batches = batch(CACHE_URLS, 20);
            return batches.reduce((p, b) => p.then(() =>
                Promise.allSettled(b.map(u => cache.add(u).catch(err => console.log('[SW] Cache miss:', u, err))))
            ), Promise.resolve());
        })
    );
    // NOTE: intentionally NOT calling self.skipWaiting() here. Activation is
    // page-controlled (mc-sw-update.js posts 'skipWaiting' only when no workout
    // is in progress) so a new build never force-reloads someone mid-set.
});

// Activate — remove old APP caches and take control (but not FONT_CACHE_NAME,
// which deliberately outlives any one deploy — see its declaration above).
// The page-side reload is driven by mc-sw-update.js's 'controllerchange'
// handler (which guards against reloading mid-workout), so we do NOT
// force-navigate tabs here.
self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys()
            .then(keys => Promise.all(
                keys.filter(k => k !== CACHE_NAME && k !== FONT_CACHE_NAME).map(k => {
                    console.log('[SW] Removing old cache:', k);
                    return caches.delete(k);
                })
            ))
            .then(() => self.clients.claim())
    );
});

// Offline fallback page (audit DG-7). Both variants share one themed shell:
// the ONE screen a trainee sees at the worst possible moment — mid-workout,
// signal just dropped — used to be hardcoded dark hex with no light variant
// and system-font text, the least-designed screen in an app that otherwise
// ships a real token system (base.css) and a governed light mode
// (mc-light.css). This mirrors both rather than inventing a third palette,
// and resolves theme with the SAME snippet index.html's own <head> boot
// script uses (mc_theme_mode, falling back to prefers-color-scheme) — a
// Response body renders as a real page once the browser paints it, so this
// inline <script> runs exactly like any other page's before-first-paint
// theme guard, even though the SW itself can't touch localStorage.
//
// Deliberately NOT 'Bebas Neue' for the wordmark (audit DG-1): that face is
// referenced in base.css's athletic theme but loaded nowhere in the app, so
// every device already renders it as a silent system-font fallback — using
// it here would be the same defect a second time. This uses the same real
// stack the rest of the app renders text in.
function offlineShell(bodyHtml) {
    return '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
        '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">' +
        '<title>MC Training — Offline</title>' +
        '<style>' +
        ':root{--bg:#0a0a0a;--card:#141414;--text:#e2e8f0;--muted:#64748b;--accent:#d4af37;--border:rgba(255,255,255,0.1);}' +
        '@media (prefers-color-scheme: light){:root:not([data-theme="dark"]){--bg:#f5f2ec;--card:#faf7f0;--text:#1c1a17;--muted:#6b6459;--accent:#8a6d1a;--border:rgba(0,0,0,0.1);}}' +
        ':root[data-theme="light"]{--bg:#f5f2ec;--card:#faf7f0;--text:#1c1a17;--muted:#6b6459;--accent:#8a6d1a;--border:rgba(0,0,0,0.1);}' +
        '*{box-sizing:border-box;}' +
        'html,body{height:100%;margin:0;}' +
        'body{background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,sans-serif;' +
        'display:flex;align-items:center;justify-content:center;padding:24px;' +
        'padding-bottom:calc(24px + env(safe-area-inset-bottom));}' +
        '.card{max-width:360px;width:100%;text-align:center;background:var(--card);border:1px solid var(--border);' +
        'border-radius:16px;padding:36px 28px;}' +
        '.mark{width:48px;height:48px;margin:0 auto 16px;color:var(--accent);}' +
        'h1{font-size:19px;font-weight:800;letter-spacing:-0.01em;margin:0 0 8px;color:var(--text);}' +
        'p{font-size:14px;line-height:1.5;color:var(--muted);margin:0 0 22px;}' +
        '.actions{display:flex;flex-direction:column;gap:10px;}' +
        'a,button{display:block;width:100%;padding:12px;border-radius:10px;font-size:14px;font-weight:700;' +
        'text-decoration:none;border:none;cursor:pointer;font-family:inherit;}' +
        '.primary{background:var(--accent);color:#000;}' +
        '.secondary{background:transparent;color:var(--muted);border:1px solid var(--border);}' +
        '</style>' +
        '<script>try{' +
        'var m=localStorage.getItem("mc_theme_mode");' +
        'var light=m?m===\'light\':!(window.matchMedia&&matchMedia("(prefers-color-scheme: dark)").matches);' +
        'document.documentElement.setAttribute("data-theme",light?"light":"dark");' +
        '}catch(e){}</script>' +
        '</head><body><div class="card">' +
        '<svg class="mark" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6">' +
        '<path d="M6.5 6.5v11M17.5 6.5v11M3 9h3.5M3 15h3.5M17.5 9H21M17.5 15H21M9 6.5h6M9 17.5h6"/></svg>' +
        bodyHtml +
        '<div class="actions">' +
        '<button class="primary" onclick="location.reload()">Try again</button>' +
        '<a class="secondary" href="dashboard.html">Back to dashboard</a>' +
        '</div></div></body></html>';
}

// Offline fallback page (shared by the HTML + asset handlers).
function offlinePage(msg) {
    return new Response(
        offlineShell('<h1>You\'re offline</h1><p>' + (msg || 'This page hasn\'t been saved for offline use yet — reconnect once to cache it.') + '</p>'),
        { headers: { 'Content-Type': 'text/html' } }
    );
}

// Offline fallback for a non-HTML asset that was never cached.
function assetOfflinePage() {
    return new Response(
        offlineShell('<h1>You\'re offline</h1><p>Open this page while online once to save it for next time.</p>'),
        { headers: { 'Content-Type': 'text/html' } }
    );
}

// Stale-while-revalidate (audit LS-4, finding W-12). Serve the cached copy
// INSTANTLY when we have one — repeat navigations and the ~25 module loads per
// workout page feel instant instead of waiting on flaky gym Wi-Fi every time —
// and refresh the cache in the background for next load.
//
// Why cache-first is correct here (not stale): this is a static site whose
// HTML/JS/CSS only ever changes with a deploy, and every deploy bumps
// CACHE_NAME. The `activate` handler above purges the old cache, and
// mc-sw-update.js reloads the page on `controllerchange` (guarded against
// mid-workout). So a new build always reaches the user via the SW-version path,
// while within a single version the cache is byte-for-byte what the server
// would send — making cache-first both instant AND fresh. First visits (nothing
// cached yet) fall through to the network, with an offline fallback.
//
// Returns { response, revalidation } so the fetch handler can respondWith the
// response and waitUntil the revalidation (keeping the SW alive to finish the
// background cache write). Split out as a pure function so tools/test-mc-sw.js
// can verify the logic with a sandboxed fetch/caches — the live fetch handler
// is guarded to the production origin and can't be exercised on localhost.
function staleWhileRevalidate(request, offlineFallback) {
    const revalidation = fetch(request).then(resp => {
        if (resp && resp.status === 200) {
            const clone = resp.clone();
            caches.open(CACHE_NAME).then(c => c.put(request, clone));
        }
        return resp;
    }).catch(() => null);
    const response = caches.match(request).then(cached =>
        cached || revalidation.then(resp => resp || offlineFallback())
    );
    return { response, revalidation };
}

// Cache-first for the app's webfont (DG-1/DG-2 — see FONT_CACHE_NAME above).
// Cache-first rather than stale-while-revalidate: Google's font URLs are
// content-addressed (a given URL's bytes never change), so there is nothing
// to revalidate — once fetched, serving the cached copy forever is correct,
// not stale. `{mode:'no-cors'}` accepts the opaque cross-origin response
// (Cache Storage can store and replay one, just never read its contents);
// omitted mode would let a CORS rejection reach the page as a broken font
// load instead of falling through to this cache.
function cacheFirstFont(request) {
    return caches.open(FONT_CACHE_NAME).then(cache =>
        cache.match(request).then(cached => {
            if (cached) return cached;
            return fetch(request, { mode: 'no-cors' }).then(resp => {
                cache.put(request, resp.clone());
                return resp;
            }).catch(() => cached);
        })
    );
}

// Fetch — stale-while-revalidate for both navigations and assets.
self.addEventListener('fetch', event => {
    const url = event.request.url;

    if (event.request.method !== 'GET') return;
    if (FONT_HOSTS.some(h => url.includes('://' + h + '/'))) {
        event.respondWith(cacheFirstFont(event.request));
        return;
    }

    // Only handle same-origin GETs (POSTs, Supabase calls, etc. pass through).
    if (!url.startsWith('https://mcross2298.github.io')) return;

    const isHTML = url.endsWith('.html') || url.endsWith('/') || !url.split('/').pop().includes('.');
    const { response, revalidation } = staleWhileRevalidate(
        event.request, isHTML ? offlinePage : assetOfflinePage
    );
    event.waitUntil(revalidation.catch(() => {}));
    event.respondWith(response);
});

// Push — show notification from server-sent milestone alert
self.addEventListener('push', event => {
    let title = 'MC Training', body = 'You have a new milestone!', icon = './icon.svg';
    try {
        if (event.data) {
            const d = event.data.json();
            if (d.title) title = d.title;
            if (d.body)  body  = d.body;
            if (d.icon)  icon  = d.icon;
        }
    } catch (_) {}
    event.waitUntil(
        self.registration.showNotification(title, {
            body,
            icon,
            badge: './icon.svg',
            tag: 'mc-milestone',
            renotify: true
        })
    );
});

// Notification click — open the dashboard
self.addEventListener('notificationclick', event => {
    event.notification.close();
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
            const dash = list.find(c => c.url.includes('dashboard.html'));
            if (dash) return dash.focus();
            return clients.openWindow('./dashboard.html');
        })
    );
});

// Message — force update
self.addEventListener('message', event => {
    if (event.data === 'skipWaiting') self.skipWaiting();
});