// MC Training — Service Worker v2
// Relative-path precache so the app works at any GitHub Pages project subpath

const CACHE_NAME = 'mc-training-market-ci-105';
const BASE = 'https://mcross2298.github.io/MC-Training-Rolodex/';
// The list below is generated by tools/build-sw.py — do not edit by hand.
const CACHE_URLS = [
    /* AUTOGEN:URLS START */
    './',
    './45-minute-burner.html',
    './base.css',
    './battle-ropes.html',
    './bonus-workouts.html',
    './boxing-routine.html',
    './build-program.html',
    './build-workout.html',
    './cat-custom.html',
    './cat-faint.html',
    './cat-ie.html',
    './cat-ks.html',
    './cat-mc.html',
    './cat-mm.html',
    './cat-pmc.html',
    './cat-strength.html',
    './collections.html',
    './conditioning-data.js',
    './conditioning-elite.css',
    './conditioning-timer.html',
    './dashboard.html',
    './driveway-demolition.html',
    './exercise-catalog.js',
    './exercise-library.html',
    './exercisedata.json',
    './faint-instructions.html',
    './full-body-pyramid.html',
    './hell-week.html',
    './icon.svg',
    './import.html',
    './index.html',
    './iron-engine.html',
    './kitchen-sink-s3.html',
    './kitchen-sink-s4.html',
    './kitchen-sink-s5.html',
    './kitchen-sink-s6.html',
    './kitchen-sink.html',
    './manifest.json',
    './max-out.html',
    './mc-account.js',
    './mc-backup-status.js',
    './mc-barcode.js',
    './mc-biomech.js',
    './mc-biometric.js',
    './mc-body.js',
    './mc-bonus-routing.js',
    './mc-calendar.js',
    './mc-card-actions.css',
    './mc-card-actions.js',
    './mc-cardio.html',
    './mc-chart.js',
    './mc-collections.js',
    './mc-cond.js',
    './mc-cues-data.js',
    './mc-cues.js',
    './mc-exercise-catalog.js',
    './mc-exercise-trends.js',
    './mc-finish.js',
    './mc-foodapi.js',
    './mc-group-split.js',
    './mc-home.html',
    './mc-instructions.html',
    './mc-interval.js',
    './mc-layout.js',
    './mc-live-tracker.js',
    './mc-macrocalc.js',
    './mc-macros.js',
    './mc-maxout.js',
    './mc-muscle-map.js',
    './mc-naming-paint.js',
    './mc-naming.js',
    './mc-nav.css',
    './mc-nav.js',
    './mc-pm-creator.js',
    './mc-pm-data.js',
    './mc-pm-inline.js',
    './mc-pm-layout-editor.js',
    './mc-program-builder.js',
    './mc-program-pub.js',
    './mc-program-store.js',
    './mc-push.js',
    './mc-recap.js',
    './mc-rep-progress.js',
    './mc-replace.js',
    './mc-reps.js',
    './mc-resume.js',
    './mc-s1-back.html',
    './mc-s1-bis-tris.html',
    './mc-s1-chest-shoulders.html',
    './mc-s1-legs.html',
    './mc-s1-legs2.html',
    './mc-s2-back.html',
    './mc-s2-chest-bis.html',
    './mc-s2-cst.html',
    './mc-s2-legs.html',
    './mc-s2-legs2.html',
    './mc-s3-back-bis-forearms.html',
    './mc-s3-back.html',
    './mc-s3-chest.html',
    './mc-s3-legs-back.html',
    './mc-s3-legs.html',
    './mc-s3-shoulders-tris.html',
    './mc-s4-bis-tris.html',
    './mc-s4-chest-tris.html',
    './mc-s4-legs.html',
    './mc-s4-shoulders.html',
    './mc-s5-legs.html',
    './mc-s5-pull.html',
    './mc-s5-push.html',
    './mc-schedule.js',
    './mc-session.js',
    './mc-setlog.css',
    './mc-setlog.js',
    './mc-share.js',
    './mc-split1.html',
    './mc-split2.html',
    './mc-split3.html',
    './mc-split4.html',
    './mc-split5.html',
    './mc-stats.js',
    './mc-suggest.js',
    './mc-summary.css',
    './mc-summary.js',
    './mc-supabase.js',
    './mc-superset-hop.js',
    './mc-sw-update.js',
    './mc-sync.js',
    './mc-theme.js',
    './mc-timer.js',
    './mc-wrapped.js',
    './mcdb.js',
    './mm-p1.html',
    './mm-p2.html',
    './mm-p3.html',
    './pm-mode-overview.html',
    './pmc-back.html',
    './pmc-bis-tris.html',
    './pmc-chest-shoulders.html',
    './pmc-data.js',
    './pmc-home.html',
    './pmc-instructions.html',
    './pmc-legs-hams.html',
    './pmc-legs-quad.html',
    './pmc-s2-back.html',
    './pmc-s2-chest-biceps.html',
    './pmc-s2-cst.html',
    './pmc-s2-legs-day2.html',
    './pmc-s2-legs-quad.html',
    './pmc-s3-back-bis-forearms.html',
    './pmc-s3-back.html',
    './pmc-s3-chest.html',
    './pmc-s3-legs.html',
    './pmc-s3-shoulders-tris.html',
    './pmc-s4-bis-tris.html',
    './pmc-s4-chest-tris.html',
    './pmc-s4-legs-back.html',
    './pmc-s4-legs-day2.html',
    './pmc-s4-shoulders.html',
    './pmc-s5-core.html',
    './pmc-s5-legs.html',
    './pmc-s5-pull.html',
    './pmc-s5-push.html',
    './pmc-s6-abs-circuit.html',
    './pmc-s6-back-traps.html',
    './pmc-s6-chest.html',
    './pmc-s6-delts-arms.html',
    './pmc-s6-legs.html',
    './pmc-s7-data.js',
    './pmc-s7-giant.html',
    './pmc-split1.html',
    './pmc-split2.html',
    './pmc-split3.html',
    './pmc-split4.html',
    './pmc-split5.html',
    './pmc-split6.html',
    './pmc-split7.html',
    './pmc-workout.html',
    './popeye.html',
    './program-guide.html',
    './program-manager.js',
    './program-overrides.js',
    './program-overrides.json',
    './quick-tour-overview.html',
    './quick-tour.html',
    './run-program.html',
    './run-workout.html',
    './stats.html',
    './superset-timers.js',
    './sw.js',
    './the-500.html',
    './turn-and-burn.html',
    './workout-logs.html',
    './wrapped.html'
    /* AUTOGEN:URLS END */
];

// Install — cache everything
self.addEventListener('install', event => {
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {
            console.log('[SW] Caching', CACHE_URLS.length, 'files');
            // Cache in batches to avoid timeout
            const batch = (arr, size) => Array.from({length:Math.ceil(arr.length/size)}, (_,i) => arr.slice(i*size,i*size+size));
            const batches = batch(CACHE_URLS, 20);
            return batches.reduce((p, b) => p.then(() =>
                Promise.allSettled(b.map(u => cache.add(u).catch(err => console.log('[SW] Cache miss:', u, err))))
            ), Promise.resolve());
        })
    );
    // NOTE: intentionally NOT calling self.skipWaiting() here. Activation is
    // page-controlled (mc-sw-update.js posts 'skipWaiting' only when no workout
    // is in progress) so a new build never force-reloads someone mid-set.
});

// Activate — remove ALL old caches and take control. The page-side reload is
// driven by mc-sw-update.js's 'controllerchange' handler (which guards against
// reloading mid-workout), so we do NOT force-navigate tabs here.
self.addEventListener('activate', event => {
    event.waitUntil(
        caches.keys()
            .then(keys => Promise.all(
                keys.filter(k => k !== CACHE_NAME).map(k => {
                    console.log('[SW] Removing old cache:', k);
                    return caches.delete(k);
                })
            ))
            .then(() => self.clients.claim())
    );
});

// Offline fallback page (shared by the HTML + asset handlers).
function offlinePage(msg) {
    return new Response(
        '<html><body style="background:#0a0a0a;color:#fff;font-family:sans-serif;text-align:center;padding:60px 20px"><h2 style="color:#d4af37">MC Training</h2><p style="color:#9ca3af;margin-top:12px">' +
        (msg || 'You are offline.') +
        '</p><a href="/" style="display:inline-block;margin-top:20px;color:#d4af37">← Home</a></body></html>',
        { headers: { 'Content-Type': 'text/html' } }
    );
}

// HTML strategy: network-FIRST so a fresh build still wins on good signal, but
// fall back to cache after a short timeout so navigations stay fast on poor gym
// signal (and the cache keeps updating in the background — fresh next load).
function htmlStrategy(request) {
    return new Promise(resolve => {
        let settled = false;
        const finish = r => { if (!settled) { settled = true; resolve(r); } };
        // After 2.5s of waiting on the network, serve cache if we have it.
        const timer = setTimeout(() => {
            caches.match(request).then(cached => { if (cached) finish(cached); });
        }, 2500);
        fetch(request).then(resp => {
            if (resp && resp.status === 200) {
                const clone = resp.clone();
                caches.open(CACHE_NAME).then(c => c.put(request, clone));
            }
            clearTimeout(timer);
            finish(resp);   // no-op if the timeout already served cache; cache was still refreshed above
        }).catch(() => {
            clearTimeout(timer);
            caches.match(request).then(cached => finish(cached || offlinePage()));
        });
    });
}

// Fetch — HTML: network-first w/ fast cache fallback. CSS/JS/assets: network-first with cache fallback.
self.addEventListener('fetch', event => {
    const url = event.request.url;

    // Only handle requests to our domain
    if (!url.startsWith('https://mcross2298.github.io')) return;

    const isHTML = url.endsWith('.html') || url.endsWith('/') || !url.split('/').pop().includes('.');
    if (isHTML) {
        event.respondWith(htmlStrategy(event.request));
        return;
    }

    // CSS/JS/assets: network-first, cache fallback
    event.respondWith(
        fetch(event.request).then(resp => {
            if (resp && resp.status === 200) {
                const clone = resp.clone();
                caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
            }
            return resp;
        }).catch(() => {
            return caches.match(event.request).then(cached => {
                if (cached) return cached;
                return new Response(
                    '<html><body style="background:#0a0a0a;color:#fff;font-family:sans-serif;text-align:center;padding:60px 20px"><h2 style="color:#d4af37">MC Training</h2><p style="color:#9ca3af;margin-top:12px">You are offline. Open this page while online to cache it.</p><a href="/" style="display:inline-block;margin-top:20px;color:#d4af37">← Home</a></body></html>',
                    {headers: {'Content-Type': 'text/html'}}
                );
            });
        })
    );
});

// Push — show notification from server-sent milestone alert
self.addEventListener('push', event => {
    let title = 'MC Training', body = 'You have a new milestone!', icon = './icon.svg';
    try {
        if (event.data) {
            const d = event.data.json();
            if (d.title) title = d.title;
            if (d.body)  body  = d.body;
            if (d.icon)  icon  = d.icon;
        }
    } catch (_) {}
    event.waitUntil(
        self.registration.showNotification(title, {
            body,
            icon,
            badge: './icon.svg',
            tag: 'mc-milestone',
            renotify: true
        })
    );
});

// Notification click — open the dashboard
self.addEventListener('notificationclick', event => {
    event.notification.close();
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
            const dash = list.find(c => c.url.includes('dashboard.html'));
            if (dash) return dash.focus();
            return clients.openWindow('./dashboard.html');
        })
    );
});

// Message — force update
self.addEventListener('message', event => {
    if (event.data === 'skipWaiting') self.skipWaiting();
});